//! Printed card data for EVERY Netrunner card, plus implementation coverage.
//!
//! The data files are generated by `tools/gen-carddata.py` from the official
//! card data (`tools/raw_data.edn`, vendored from netrunner-data) and from a
//! scan of the reference implementation's `defcard` forms — see
//! docs/CARD-COVERAGE.md for the pipeline. This module only embeds and
//! indexes them; the behavior overlay lives in `carddb.rs`.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

static CARDS_JSON: &str = include_str!("../carddata/cards.json");
static COVERAGE_JSON: &str = include_str!("../carddata/coverage.json");

/// Printed (as-on-cardboard) data for one card title, latest printing.
#[derive(Debug, Clone, Deserialize)]
pub struct PrintedCard {
    pub title: String,
    pub code: String,
    pub side: String,
    #[serde(rename = "type")]
    pub card_type: String,
    pub faction: Option<String>,
    #[serde(default)]
    pub subtypes: Vec<String>,
    pub text: Option<String>,
    pub cost: Option<i64>,
    pub strength: Option<i64>,
    pub memoryunits: Option<i64>,
    pub trash_cost: Option<i64>,
    pub advancement_requirement: Option<i64>,
    pub agenda_points: Option<i64>,
    pub base_link: Option<i64>,
    #[serde(default)]
    pub uniqueness: bool,
    pub deck_limit: Option<i64>,
    pub set: Option<String>,
    pub cycle: Option<String>,
    #[serde(default)]
    pub rotated: bool,
}

fn printed_vec() -> &'static Vec<PrintedCard> {
    static DATA: OnceLock<Vec<PrintedCard>> = OnceLock::new();
    DATA.get_or_init(|| {
        serde_json::from_str(CARDS_JSON).expect("carddata/cards.json is valid")
    })
}

fn printed_index() -> &'static HashMap<&'static str, usize> {
    static INDEX: OnceLock<HashMap<&'static str, usize>> = OnceLock::new();
    INDEX.get_or_init(|| {
        printed_vec()
            .iter()
            .enumerate()
            .map(|(i, c)| (c.title.as_str(), i))
            .collect()
    })
}

/// Every card in the database (sorted by title).
pub fn all_printed() -> &'static [PrintedCard] {
    printed_vec()
}

/// Printed data for a title, if the card exists.
pub fn printed(title: &str) -> Option<&'static PrintedCard> {
    printed_index().get(title).map(|&i| &printed_vec()[i])
}

/// Printed rules text for a title, if the card exists and has text.
pub fn printed_text(title: &str) -> Option<&'static str> {
    printed(title).and_then(|p| p.text.as_deref())
}

// ── coverage ───────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, Deserialize)]
pub struct CoverageRow {
    /// The reference implementation has a `(defcard "Title" ...)` form.
    pub jnet_impl: bool,
    /// That defcard carries an `:implementation` caveat note.
    pub jnet_partial: bool,
    /// Title present in the Rust behavior table (`carddb::CARDS`).
    pub rs_behavior: bool,
}

#[derive(Debug, Deserialize)]
struct CoverageFile {
    cards: HashMap<String, CoverageRow>,
    #[serde(default)]
    jnet_extra_titles: Vec<String>,
}

fn coverage() -> &'static CoverageFile {
    static DATA: OnceLock<CoverageFile> = OnceLock::new();
    DATA.get_or_init(|| {
        serde_json::from_str(COVERAGE_JSON).expect("carddata/coverage.json is valid")
    })
}

/// Coverage flags for a title, if the card exists.
pub fn coverage_row(title: &str) -> Option<CoverageRow> {
    coverage().cards.get(title).copied()
}

/// Reference defcard titles that are not real cards (jnet pseudo-cards such
/// as the Basic Action Cards).
pub fn jnet_extra_titles() -> &'static [String] {
    &coverage().jnet_extra_titles
}

/// Where a title's rules live.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImplStatus {
    /// Full behavior in the Rust engine (`carddb::CARDS` overlay).
    Behavior,
    /// jinteki.net implements it but we have no Rust behavior yet — the
    /// bridge-to-jnet-appropriate set. The engine plays it as vanilla.
    JnetOnly,
    /// Not implemented even by jinteki.net — the ISOLATED set needing fresh
    /// behavior work.
    Unimplemented,
}

/// Implementation status for a title. The live behavior table wins over the
/// generated coverage snapshot, so a freshly added `CardDef` row is
/// `Behavior` even before regeneration.
pub fn impl_status(title: &str) -> ImplStatus {
    if crate::carddb::def_by_title(title).is_some() {
        return ImplStatus::Behavior;
    }
    match coverage().cards.get(title) {
        Some(row) if row.jnet_impl => ImplStatus::JnetOnly,
        _ => ImplStatus::Unimplemented,
    }
}
